### ISSUE TITLE
Cannot install with custom User model

### ISSUE THREAD

**Issue by ishankhare07** [BobBowles/django-diary#3]
Hi, I have a custom user model defined. For this reason I already have `settings.AUTH_USER_MODEL` set.
But going through the installation docs, when I run `manage.py migrate` I get the following error:

```
ERRORS:
diary.Customer.user_ptr: (fields.E301) Field defines a relation with the model 'auth.User', which has been swapped out.
        HINT: Update the relation to point at 'settings.AUTH_USER_MODEL'.
diary.Entry.creator: (fields.E301) Field defines a relation with the model 'auth.User', which has been swapped out.
        HINT: Update the relation to point at 'settings.AUTH_USER_MODEL'.
diary.Entry.editor: (fields.E301) Field defines a relation with the model 'auth.User', which has been swapped out.
        HINT: Update the relation to point at 'settings.AUTH_USER_MODEL'.
```

Currently I've already set `settings.AUTH_USER_MODEL='core.User'`
